package one.rarebit.heyarr.mobile

import one.rarebit.heyarr.core.auth.Credential
import one.rarebit.voidwhichbinds.Cert
import one.rarebit.voidwhichbinds.Ed25519Signer
import one.rarebit.voidwhichbinds.Ed25519Verifier
import one.rarebit.voidwhichbinds.auth.DeviceCredential
import one.rarebit.voidwhichbinds.auth.PossessionProof
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec

/**
 * Software Ed25519 for tests, via the JDK provider (JDK 15+): raw 32-byte seeds and
 * public keys wrapped in the fixed PKCS#8 / SPKI prefixes. Stands in for the phone's
 * hardware-sealed `DeviceKeyStore` — same signature bytes, no enclave.
 */
object JdkEd25519 {
    private val PKCS8_PREFIX = hex("302e020100300506032b657004220420")
    private val SPKI_PREFIX = hex("302a300506032b6570032100")

    fun privateKey(seed: ByteArray): PrivateKey =
        KeyFactory.getInstance("Ed25519").generatePrivate(PKCS8EncodedKeySpec(PKCS8_PREFIX + seed))

    fun publicKey(raw: ByteArray): PublicKey =
        KeyFactory.getInstance("Ed25519").generatePublic(X509EncodedKeySpec(SPKI_PREFIX + raw))

    fun sign(seed: ByteArray, message: ByteArray): ByteArray = Signature.getInstance("Ed25519").run {
        initSign(privateKey(seed))
        update(message)
        sign()
    }

    val verifier = Ed25519Verifier { pub, message, sig ->
        runCatching {
            Signature.getInstance("Ed25519").run {
                initVerify(publicKey(pub))
                update(message)
                verify(sig)
            }
        }.getOrDefault(false)
    }

    fun hex(s: String): ByteArray = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
}

/**
 * Cross-language vectors against the Go implementation heyarr-core runs
 * (voidbind-go v0.5.0 `enrolment`). Both were minted by the real Go code with fixed
 * seeds and clocks (Ed25519 is deterministic), so a byte-for-byte match here proves
 * the proof this app presents is what `deviceauth.Verify` accepts. The implementation
 * is voidbind-client's `auth/` (since 0.4.0 — the app's own port was deleted); these
 * vectors stay HERE so a library bump that drifts the wire format fails this app's
 * CI, not just the library's. If a constant ever has to change to make this pass,
 * the wire format broke — stop and investigate.
 *
 * The one deliberate change: void-which-binds-client 0.10.0 carries ADR-0009 phase 2, so
 * the minter now puts `"typ":"voidbind.possession"` in every proof. Vector B moved to the
 * Go typed device-scheme vector (void-which-binds-go >= v0.16 verifies it), and untyped
 * vector A is now verify-only — the legacy proof still verifies.
 */
// The vectors are pinned verbatim, so their lines can't wrap. The new ones change both the
// line numbers (ktlint's baseline is line-keyed) and the text (detekt's is signature-keyed),
// so they are exempted here rather than re-baselined.
@Suppress("MaxLineLength", "ktlint:standard:max-line-length")
class PossessionProofTest {

    // Vector A (legacy, untyped) — heyarr-core's own crosscompat golden cert (user seed
    // 0x01*32, device seed 0x02*32, iat 1700000000) + a proof minted by Go
    // `SignPossession(dev, cert, 1700000000, 0)` before ADR-0009 phase 2 (scratch Go program).
    private val certA = "eyJ2IjoyLCJ1c3IiOiJlZDI1NTE5OjhhODhlM2RkNzQwOWYxOTVmZDUyZGIyZDNjYmE1ZDcyY2E2NzA5YmYxZDk0MTIxYmYzNzQ4ODAxYjQwZjZmNWMiLCJkZXYiOiJlZDI1NTE5OjgxMzk3NzBlYTg3ZDE3NWY1NmEzNTQ2NmMzNGM3ZWNjY2I4ZDhhOTFiNGVlMzdhMjVkZjYwZjViOGZjOWIzOTQiLCJkZW5jIjoieDI1NTE5OjAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwNzc3NjAwMH0.yUnLKnvDZ8YtkgV9zf5eRrYHes5osqzzGlVHXcFSPiuIuVM0jmcdGH4qOQA-UCla_9qwSK7VPpXSfsTbSY_JBA"
    private val proofA = "eyJ2IjoyLCJjcnQiOiJsQ2ViWTBpTTM0SGM0Z3RGUERtZ1o2S0pMWWE0ejc0YklhU1hSWFV1d01ZIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjE3MDAwMDAxMjB9.2Ta_JOte2RDRHBFrNvOToo68--ea7TIfRjFPNGV-JtvQiXVb_hfE1gQCA9RwlbHyFJ9Mp0AZ5G_u19U1jB-FAg"
    private val nowA = 1_700_000_000L

    // Vector B — the device-scheme vector as minted since ADR-0009 phase 2 (void-which-binds-go
    // `testvectors/vectors/device-scheme-vector-typed.json`, generated by
    // enrolment.TestDeviceSchemeVector; device seed 0x80..0x9f, cert iat 1788307200,
    // possession now 1788350400): `typ` in both the cert and the possession proof. Since
    // client 0.10.0 the Kotlin minter emits `typ`, so THIS is the proof the app presents.
    private val certB = "eyJ2IjoyLCJ0eXAiOiJ2b2lkYmluZC5jZXJ0IiwidXNyIjoiZWQyNTUxOTowM2ExMDdiZmYzY2UxMGJlMWQ3MGRkMThlNzRiYzA5OTY3ZTRkNjMwOWJhNTBkNWYxZGRjODY2NDEyNTUzMWI4IiwiZGV2IjoiZWQyNTUxOTpjZDE0YjM3Zjk1NmU5NTMxOTRmZjdmYjczYjNkODFkY2M1NjFkNjFhNzUzODA5NGI3YzNlMWE2NDNlZTVmM2FhIiwiZGVuYyI6IngyNTUxOTowMDExMjIzMzQ0NTU2Njc3ODg5OWFhYmJjY2RkZWVmZjAwMTEyMjMzNDQ1NTY2Nzc4ODk5YWFiYmNjZGRlZWZmIiwiaWF0IjoxNzg4MzA3MjAwLCJleHAiOjE3OTYwODMyMDB9.ilXUzCfZiDujpgRY-hxOOhDYwIoWdbCvkAVAWsjYpHMr3aoanr9POUSqYkYjyS-qIhxnivB-5cpHONzYCpZaAg"
    private val proofB = "eyJ2IjoyLCJ0eXAiOiJ2b2lkYmluZC5wb3NzZXNzaW9uIiwiY3J0Ijoib2F1UHlXQ2FYckVwWW1mM01tdUM5Q2ppTTdLZGxYVGtKaWRjN0o0OG1EUSIsImlhdCI6MTc4ODM1MDQwMCwiZXhwIjoxNzg4MzUwNTIwfQ.bzgcN04eLQxso30rjoeCLUO8eGLGIY1WisbnIboa2o5IXvlI-yG8flGSDJl5hHgz_mP2y1yON8RJfkZVo75RAA"
    private val deviceSeedB = JdkEd25519.hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
    private val nowB = 1_788_350_400L

    private fun signer(seed: ByteArray) = Ed25519Signer { JdkEd25519.sign(seed, it) }

    @Test fun signingBytesMatchGoJson() {
        assertEquals(
            """{"v":2,"typ":"voidbind.possession","crt":"oauPyWCaXrEpYmf3MmuC9CjiM7KdlXTkJidc7J48mDQ","iat":1788350400,"exp":1788350520}""",
            PossessionProof.signingBytes(certB, nowB, nowB + 120).decodeToString(),
        )
        assertEquals("lCebY0iM34Hc4gtFPDmgZ6KJLYa4z74bIaSXRXUuwMY", PossessionProof.certHash(certA))
    }

    @Test fun stillVerifiesTheLegacyUntypedGoProof_vectorA() {
        // ADR-0009: an untyped proof minted before phase 2 still verifies (the minter
        // now always emits typ, so the app can no longer reproduce vector A's bytes).
        PossessionProof.verify(proofA, devicePub(certA), certA, nowA + 1, JdkEd25519.verifier)
    }

    @Test fun mintsTheExactGoTypedProof_vectorB() {
        assertEquals(proofB, PossessionProof.mint(certB, signer(deviceSeedB), nowB))
    }

    @Test fun fullCredentialMatchesTheVector() {
        val minted = DeviceCredential.mint(certB, signer(deviceSeedB), nowB)
        assertEquals("Device $certB~$proofB", minted.headerValue)
        // The app's own Credential.Device renders through the library — same bytes.
        assertEquals(minted.headerValue, Credential.Device(minted.cert, minted.proof).headerValue())
        val (c, p) = DeviceCredential.parse(DeviceCredential.format(minted.cert, minted.proof))
        assertEquals(certB, c)
        assertEquals(proofB, p)
    }

    @Test fun certVectorsParseAndVerifyAgainstTheirUserKey() {
        for (token in listOf(certA, certB)) {
            val parsed = Cert.parse(token)
            assertEquals(2, parsed.cert.version)
            assertTrue("cert signature by usr", parsed.verify(JdkEd25519.verifier))
        }
        // The device key named by the cert is the one our seed derives — else a proof could never verify.
        assertEquals(
            Cert.parse(certB).cert.device.render(),
            "ed25519:cd14b37f956e953194ff7fb73b3d81dcc561d61a7538094b7c3e1a643ee5f3aa",
        )
    }

    private fun devicePub(token: String) = Cert.parse(token).cert.device.bytes

    @Test fun verifyMirrorsGoWindow() {
        val pub = devicePub(certA)
        // honoured 1s before expiry; expired AT ttl (strict); honoured half a skew early; refused 2 skews early
        PossessionProof.verify(proofA, pub, certA, nowA + 119, JdkEd25519.verifier)
        assertEquals(
            PossessionProof.Reason.EXPIRED,
            refused {
                PossessionProof.verify(proofA, pub, certA, nowA + 120, JdkEd25519.verifier)
            },
        )
        PossessionProof.verify(proofA, pub, certA, nowA - 15, JdkEd25519.verifier)
        assertEquals(
            PossessionProof.Reason.NOT_YET_VALID,
            refused {
                PossessionProof.verify(
                    proofA,
                    pub,
                    certA,
                    nowA - 60,
                    JdkEd25519.verifier,
                )
            },
        )
    }

    @Test fun verifyRefusesWrongCertAndTamperedBody() {
        val pub = devicePub(certA)
        assertEquals(
            PossessionProof.Reason.WRONG_CERT,
            refused {
                PossessionProof.verify(proofA, pub, certB, nowA + 1, JdkEd25519.verifier)
            },
        )
        val flipped = proofA.substring(0, 5) + (if (proofA[5] == 'A') 'B' else 'A') + proofA.substring(6)
        assertEquals(
            PossessionProof.Reason.BAD_SIGNATURE,
            refused {
                PossessionProof.verify(
                    flipped,
                    pub,
                    certA,
                    nowA + 1,
                    JdkEd25519.verifier,
                )
            },
        )
        assertEquals(
            PossessionProof.Reason.MALFORMED,
            refused {
                PossessionProof.verify("no-dot", pub, certA, nowA + 1, JdkEd25519.verifier)
            },
        )
    }

    private fun refused(block: () -> Unit): PossessionProof.Reason =
        assertThrows(PossessionProof.Refused::class.java) { block() }.reason

    @Test fun sessionCredentialHeaderValueUnchanged() {
        assertEquals("Bearer tok", Credential.Session("tok").headerValue())
    }
}
