package one.rarebit.heyarr.mobile

import one.rarebit.heyarr.core.auth.Credential
import one.rarebit.voidwhichbinds.Cert
import one.rarebit.voidwhichbinds.Ed25519Signer
import one.rarebit.voidwhichbinds.Ed25519Verifier
import one.rarebit.voidwhichbinds.auth.DeviceCredential
import one.rarebit.voidwhichbinds.auth.PossessionProof
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec

/**
 * Software Ed25519 for tests, via the JDK provider (JDK 15+): raw 32-byte seeds and
 * public keys wrapped in the fixed PKCS#8 / SPKI prefixes. Stands in for the phone's
 * hardware-sealed `DeviceKeyStore` — same signature bytes, no enclave.
 */
object JdkEd25519 {
    private val PKCS8_PREFIX = hex("302e020100300506032b657004220420")
    private val SPKI_PREFIX = hex("302a300506032b6570032100")

    fun privateKey(seed: ByteArray): PrivateKey =
        KeyFactory.getInstance("Ed25519").generatePrivate(PKCS8EncodedKeySpec(PKCS8_PREFIX + seed))

    fun publicKey(raw: ByteArray): PublicKey =
        KeyFactory.getInstance("Ed25519").generatePublic(X509EncodedKeySpec(SPKI_PREFIX + raw))

    fun sign(seed: ByteArray, message: ByteArray): ByteArray = Signature.getInstance("Ed25519").run {
        initSign(privateKey(seed))
        update(message)
        sign()
    }

    val verifier = Ed25519Verifier { pub, message, sig ->
        runCatching {
            Signature.getInstance("Ed25519").run {
                initVerify(publicKey(pub))
                update(message)
                verify(sig)
            }
        }.getOrDefault(false)
    }

    fun hex(s: String): ByteArray = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
}

/**
 * Cross-language vectors against the Go implementation heyarr-core runs
 * (void-which-binds-go `enrolment`). Both were minted by the real Go code with fixed
 * seeds and clocks (Ed25519 is deterministic), so a byte-for-byte match here proves
 * the proof this app presents is what `deviceauth.Verify` accepts. The implementation
 * is void-which-binds-client's `auth/` (since 0.4.0 — the app's own port was deleted); these
 * vectors stay HERE so a library bump that drifts the wire format fails this app's
 * CI, not just the library's. If a constant ever has to change to make this pass,
 * the wire format broke — stop and investigate.
 *
 * The one deliberate change: void-which-binds-client 0.11.0 is gen2-only (void-which-binds-go
 * v0.19.0, ADR-0022). The minter's `typ` is `void-which-binds.possession` and the cert's
 * `void-which-binds.cert`, so vector B is Go v0.19.0's gen2 device-scheme vector, and a gen1
 * token — untyped (vector A) or `voidbind.*`-typed — is refused, never verified.
 */
// The vectors are pinned verbatim, so their lines can't wrap. The new ones change both the
// line numbers (ktlint's baseline is line-keyed) and the text (detekt's is signature-keyed),
// so they are exempted here rather than re-baselined.
@Suppress("MaxLineLength", "ktlint:standard:max-line-length")
class PossessionProofTest {

    // Vector A (gen1, untyped) — heyarr-core's own crosscompat golden cert (user seed
    // 0x01*32, device seed 0x02*32, iat 1700000000) + a proof minted by Go
    // `SignPossession(dev, cert, 1700000000, 0)` before ADR-0009 phase 2 (scratch Go program).
    // Kept only to prove gen2 REFUSES it: gen2 is typed-only (ADR-0022).
    private val certA = "eyJ2IjoyLCJ1c3IiOiJlZDI1NTE5OjhhODhlM2RkNzQwOWYxOTVmZDUyZGIyZDNjYmE1ZDcyY2E2NzA5YmYxZDk0MTIxYmYzNzQ4ODAxYjQwZjZmNWMiLCJkZXYiOiJlZDI1NTE5OjgxMzk3NzBlYTg3ZDE3NWY1NmEzNTQ2NmMzNGM3ZWNjY2I4ZDhhOTFiNGVlMzdhMjVkZjYwZjViOGZjOWIzOTQiLCJkZW5jIjoieDI1NTE5OjAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwNzc3NjAwMH0.yUnLKnvDZ8YtkgV9zf5eRrYHes5osqzzGlVHXcFSPiuIuVM0jmcdGH4qOQA-UCla_9qwSK7VPpXSfsTbSY_JBA"
    private val proofA = "eyJ2IjoyLCJjcnQiOiJsQ2ViWTBpTTM0SGM0Z3RGUERtZ1o2S0pMWWE0ejc0YklhU1hSWFV1d01ZIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjE3MDAwMDAxMjB9.2Ta_JOte2RDRHBFrNvOToo68--ea7TIfRjFPNGV-JtvQiXVb_hfE1gQCA9RwlbHyFJ9Mp0AZ5G_u19U1jB-FAg"
    private val nowA = 1_700_000_000L

    // Vector B — the gen2 device-scheme vector (void-which-binds-go v0.19.0
    // `testvectors/vectors/device-scheme-vector.json`, generated by
    // enrolment.TestDeviceSchemeVector; device seed 0x80..0x9f, cert iat 1788307200,
    // possession now 1788350400): `void-which-binds.*` typ in both the cert and the possession
    // proof. THIS is the proof the app presents.
    private val certB = "eyJ2IjoyLCJ0eXAiOiJ2b2lkLXdoaWNoLWJpbmRzLmNlcnQiLCJ1c3IiOiJlZDI1NTE5OjAzYTEwN2JmZjNjZTEwYmUxZDcwZGQxOGU3NGJjMDk5NjdlNGQ2MzA5YmE1MGQ1ZjFkZGM4NjY0MTI1NTMxYjgiLCJkZXYiOiJlZDI1NTE5OmNkMTRiMzdmOTU2ZTk1MzE5NGZmN2ZiNzNiM2Q4MWRjYzU2MWQ2MWE3NTM4MDk0YjdjM2UxYTY0M2VlNWYzYWEiLCJkZW5jIjoieDI1NTE5OjAwMTEyMjMzNDQ1NTY2Nzc4ODk5YWFiYmNjZGRlZWZmMDAxMTIyMzM0NDU1NjY3Nzg4OTlhYWJiY2NkZGVlZmYiLCJpYXQiOjE3ODgzMDcyMDAsImV4cCI6MTc5NjA4MzIwMH0.j8lN2bHcHRnUh-01C9wzZ5MeH6VlquX98QmzHGw210af4sU6_onRYVTwAgHR21XZZCg1wNhzgpnOXni1-c3cCA"
    private val proofB = "eyJ2IjoyLCJ0eXAiOiJ2b2lkLXdoaWNoLWJpbmRzLnBvc3Nlc3Npb24iLCJjcnQiOiJJTVdqZ1BEeFlZcHpEeVQ4RGJQcFBwVENKakJEY2lDc3QzNEdSQWpFUHowIiwiaWF0IjoxNzg4MzUwNDAwLCJleHAiOjE3ODgzNTA1MjB9.m79EwR8_djhsdo4PF2LFgXGptgQP-KWcZ1z9bt7ZHNy0gA9IRWUEZOzKIw5H3nPdlHYSKEqocjLSb90ktoGyAA"
    private val deviceSeedB = JdkEd25519.hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
    private val nowB = 1_788_350_400L

    private fun signer(seed: ByteArray) = Ed25519Signer { JdkEd25519.sign(seed, it) }

    @Test fun signingBytesMatchGoJson() {
        assertEquals(
            """{"v":2,"typ":"void-which-binds.possession","crt":"IMWjgPDxYYpzDyT8DbPpPpTCJjBDciCst34GRAjEPz0","iat":1788350400,"exp":1788350520}""",
            PossessionProof.signingBytes(certB, nowB, nowB + 120).decodeToString(),
        )
        assertEquals("lCebY0iM34Hc4gtFPDmgZ6KJLYa4z74bIaSXRXUuwMY", PossessionProof.certHash(certA))
    }

    @Test fun refusesTheGen1UntypedGoProof_vectorA() {
        // ADR-0022: gen2 has no gen1 reader. An untyped proof is WRONG_TYPE before its
        // signature is even checked, and an untyped cert does not parse.
        assertEquals(
            PossessionProof.Reason.WRONG_TYPE,
            refused { PossessionProof.verify(proofA, ByteArray(32), certA, nowA + 1, JdkEd25519.verifier) },
        )
        assertThrows(IllegalArgumentException::class.java) { Cert.parse(certA) }
    }

    @Test fun mintsTheExactGoTypedProof_vectorB() {
        assertEquals(proofB, PossessionProof.mint(certB, signer(deviceSeedB), nowB))
    }

    @Test fun fullCredentialMatchesTheVector() {
        val minted = DeviceCredential.mint(certB, signer(deviceSeedB), nowB)
        assertEquals("Device $certB~$proofB", minted.headerValue)
        assertEquals(
            "Authorization: Device eyJ2IjoyLCJ0eXAiOiJ2b2lkLXdoaWNoLWJpbmRzLmNlcnQiLCJ1c3IiOiJlZDI1NTE5OjAzYTEwN2JmZjNjZTEwYmUxZDcwZGQxOGU3NGJjMDk5NjdlNGQ2MzA5YmE1MGQ1ZjFkZGM4NjY0MTI1NTMxYjgiLCJkZXYiOiJlZDI1NTE5OmNkMTRiMzdmOTU2ZTk1MzE5NGZmN2ZiNzNiM2Q4MWRjYzU2MWQ2MWE3NTM4MDk0YjdjM2UxYTY0M2VlNWYzYWEiLCJkZW5jIjoieDI1NTE5OjAwMTEyMjMzNDQ1NTY2Nzc4ODk5YWFiYmNjZGRlZWZmMDAxMTIyMzM0NDU1NjY3Nzg4OTlhYWJiY2NkZGVlZmYiLCJpYXQiOjE3ODgzMDcyMDAsImV4cCI6MTc5NjA4MzIwMH0.j8lN2bHcHRnUh-01C9wzZ5MeH6VlquX98QmzHGw210af4sU6_onRYVTwAgHR21XZZCg1wNhzgpnOXni1-c3cCA~eyJ2IjoyLCJ0eXAiOiJ2b2lkLXdoaWNoLWJpbmRzLnBvc3Nlc3Npb24iLCJjcnQiOiJJTVdqZ1BEeFlZcHpEeVQ4RGJQcFBwVENKakJEY2lDc3QzNEdSQWpFUHowIiwiaWF0IjoxNzg4MzUwNDAwLCJleHAiOjE3ODgzNTA1MjB9.m79EwR8_djhsdo4PF2LFgXGptgQP-KWcZ1z9bt7ZHNy0gA9IRWUEZOzKIw5H3nPdlHYSKEqocjLSb90ktoGyAA",
            "Authorization: ${minted.headerValue}",
        )
        // The app's own Credential.Device renders through the library — same bytes.
        assertEquals(minted.headerValue, Credential.Device(minted.cert, minted.proof).headerValue())
        val (c, p) = DeviceCredential.parse(DeviceCredential.format(minted.cert, minted.proof))
        assertEquals(certB, c)
        assertEquals(proofB, p)
    }

    @Test fun certVectorParsesAndVerifiesAgainstItsUserKey() {
        val parsed = Cert.parse(certB)
        assertEquals(2, parsed.cert.version)
        assertTrue("cert signature by usr", parsed.verify(JdkEd25519.verifier))
        assertEquals(
            "ed25519:03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8",
            parsed.cert.user.render(),
        )
        // The device key named by the cert is the one our seed derives — else a proof could never verify.
        assertEquals(
            parsed.cert.device.render(),
            "ed25519:cd14b37f956e953194ff7fb73b3d81dcc561d61a7538094b7c3e1a643ee5f3aa",
        )
    }

    private fun devicePub(token: String) = Cert.parse(token).cert.device.bytes

    @Test fun verifyMirrorsGoWindow() {
        val pub = devicePub(certB)
        // honoured 1s before expiry; expired AT ttl (strict); honoured half a skew early; refused 2 skews early
        PossessionProof.verify(proofB, pub, certB, nowB + 119, JdkEd25519.verifier)
        assertEquals(
            PossessionProof.Reason.EXPIRED,
            refused {
                PossessionProof.verify(proofB, pub, certB, nowB + 120, JdkEd25519.verifier)
            },
        )
        PossessionProof.verify(proofB, pub, certB, nowB - 15, JdkEd25519.verifier)
        assertEquals(
            PossessionProof.Reason.NOT_YET_VALID,
            refused {
                PossessionProof.verify(
                    proofB,
                    pub,
                    certB,
                    nowB - 60,
                    JdkEd25519.verifier,
                )
            },
        )
    }

    @Test fun verifyRefusesWrongCertAndTamperedBody() {
        val pub = devicePub(certB)
        assertEquals(
            PossessionProof.Reason.WRONG_CERT,
            refused {
                PossessionProof.verify(proofB, pub, certA, nowB + 1, JdkEd25519.verifier)
            },
        )
        val flipped = proofB.substring(0, 5) + (if (proofB[5] == 'A') 'B' else 'A') + proofB.substring(6)
        assertEquals(
            PossessionProof.Reason.BAD_SIGNATURE,
            refused {
                PossessionProof.verify(
                    flipped,
                    pub,
                    certB,
                    nowB + 1,
                    JdkEd25519.verifier,
                )
            },
        )
        assertEquals(
            PossessionProof.Reason.MALFORMED,
            refused {
                PossessionProof.verify("no-dot", pub, certB, nowB + 1, JdkEd25519.verifier)
            },
        )
    }

    private fun refused(block: () -> Unit): PossessionProof.Reason =
        assertThrows(PossessionProof.Refused::class.java) { block() }.reason

    @Test fun sessionCredentialHeaderValueUnchanged() {
        assertEquals("Bearer tok", Credential.Session("tok").headerValue())
    }
}
